import type { Config } from "tailwindcss";
const config: Config = {
 darkMode: "class",
 content: ["./app/**/*.{js,ts,jsx,tsx,mdx}","./components/**/*.{js,ts,jsx,tsx,mdx}","./content/**/*.{js,ts,jsx,tsx}"],
 theme: { extend: {
 colors: {
 "error-container":"#93000a","surface-container-lowest":"#080e19","error":"#ffb4ab","inverse-surface":"#dde2f3","background":"#0d131f","surface-dim":"#0d131f","secondary-fixed-dim":"#ffb59b","tertiary-fixed-dim":"#7bd0ff","primary-fixed":"#b6ebff","surface-tint":"#47d6ff","surface-container-high":"#242a36","on-error-container":"#ffdad6","on-secondary-container":"#501600","on-primary-container":"#00566a","on-background":"#dde2f3","surface":"#0d131f","tertiary-container":"#6bccff","surface-container":"#1a202b","tertiary-fixed":"#c4e7ff","surface-container-highest":"#2f3541","secondary":"#ffb59b","surface-container-low":"#161c27","on-tertiary":"#00354a","on-secondary":"#5b1a00","on-tertiary-fixed-variant":"#004c69","outline":"#859399","on-primary":"#003543","primary-container":"#00d2ff","secondary-container":"#fb5b11","primary":"#a5e7ff","on-error":"#690005","on-primary-fixed":"#001f28","inverse-primary":"#00677f","on-tertiary-fixed":"#001e2c","on-surface":"#dde2f3","on-primary-fixed-variant":"#004e60","primary-fixed-dim":"#47d6ff","outline-variant":"#3c494e","on-secondary-fixed-variant":"#812900","surface-bright":"#333946","inverse-on-surface":"#2a303d","surface-variant":"#2f3541","on-tertiary-container":"#005575","on-surface-variant":"#bbc9cf","on-secondary-fixed":"#380d00","tertiary":"#b8e3ff","secondary-fixed":"#ffdbcf"
 },
 borderRadius:{DEFAULT:"0.25rem",lg:"0.5rem",xl:"0.75rem",full:"9999px"},
 spacing:{"space-xs":"0.25rem","space-sm":"0.5rem","space-md":"1rem","space-lg":"1.5rem","space-xl":"2.5rem","gutter-sm":"1rem","gutter":"1.5rem","margin-sm":"1rem","margin":"2rem"},
 fontFamily:{"label-lg":["var(--font-jakarta)"],"headline-md":["var(--font-jakarta)"],"display-lg":["var(--font-jakarta)"],"display-lg-mobile":["var(--font-jakarta)"],"body-sm":["var(--font-jakarta)"],"label-md":["var(--font-jakarta)"],"body-lg":["var(--font-jakarta)"],"headline-sm":["var(--font-jakarta)"],"label-sm":["var(--font-jakarta)"],"body-md":["var(--font-jakarta)"],"headline-lg":["var(--font-jakarta)"],"headline-lg-mobile":["var(--font-jakarta)"]},
 fontSize:{"label-lg":["14px",{lineHeight:"20px",letterSpacing:"0.04em",fontWeight:"600"}],"headline-md":["24px",{lineHeight:"32px",letterSpacing:"-0.01em",fontWeight:"700"}],"display-lg":["56px",{lineHeight:"64px",letterSpacing:"-0.03em",fontWeight:"800"}],"display-lg-mobile":["36px",{lineHeight:"44px",letterSpacing:"-0.02em",fontWeight:"800"}],"body-sm":["13px",{lineHeight:"20px",fontWeight:"400"}],"label-md":["12px",{lineHeight:"16px",letterSpacing:"0.06em",fontWeight:"600"}],"body-lg":["18px",{lineHeight:"28px",fontWeight:"400"}],"headline-sm":["20px",{lineHeight:"28px",fontWeight:"600"}],"label-sm":["11px",{lineHeight:"14px",letterSpacing:"0.08em",fontWeight:"700"}],"body-md":["15px",{lineHeight:"24px",fontWeight:"400"}],"headline-lg":["36px",{lineHeight:"44px",letterSpacing:"-0.02em",fontWeight:"700"}],"headline-lg-mobile":["28px",{lineHeight:"36px",letterSpacing:"-0.01em",fontWeight:"700"}]}
 }}, plugins: [] };
export default config;
